name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Azure CLI Action
      uses: Azure/cli@v1.0.0
      with:
        # Specify the script here
        inlineScript: "az graph query -q 'Resources | project name, type | limit 5"
      
